### ISSUE TITLE
Unset hostname

### ISSUE THREAD

**Issue by IlyaBizyaev** [ahmadsamir/ahmadsamir.github.io#2]
https://github.com/ahmadsamir/ahmadsamir.github.io/blob/cb82a75a98fb0d1d279ca0b146414b4ac4d4d0af/_config.yml#L30

This results in broken links on planet.kde.org (see [this](https://t.me/kdeplanet/300)).

**Comment by ahmadsamir** [comment]
I commented it out, thanks :)

https://github.com/ahmadsamir/ahmadsamir.github.io/commit/9fd6ac072eaba47ee87edfe74b6dd0faf1df9e3e

**Comment by IlyaBizyaev** [comment]
It needs to be filled, not commented out.

**Comment by ahmadsamir** [comment]
> It needs to be filled, not commented out.

Err, OK; thanks for following up on this.
